# Generated by Django 5.1.3 on 2024-11-07 06:31

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fastfood', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('delivery_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('latitude', models.DecimalField(blank=True, decimal_places=13, max_digits=17, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=13, max_digits=17, null=True)),
                ('fastfood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastfood.fastfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
