# Generated by Django 5.1.3 on 2024-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_password_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(height_field=5000, upload_to='', width_field=5000),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[(1, 'Super admin'), (2, 'Officiant'), (3, 'User')], default=3, max_length=1),
        ),
    ]
