# Generated by Django 5.1.3 on 2024-11-07 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('total', models.IntegerField(blank=True, default=0)),
                ('delivery_time', models.IntegerField(blank=True, default=0)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='order.order')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='product.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
