# Generated by Django 5.1.3 on 2024-11-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fastfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=13, max_digits=17, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=13, max_digits=17, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FastFoodParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fastfood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastfood', to='fastfood.fastfood')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastfoodparent', to='product.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
